FROM golang:1.24 AS build
WORKDIR /src

COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o /out/go-translation-pipeline ./workflow/cmd/go-translation-pipeline

FROM debian:bookworm-slim
WORKDIR /workspace
COPY --from=build /out/go-translation-pipeline /usr/local/bin/go-translation-pipeline
ENTRYPOINT ["/usr/local/bin/go-translation-pipeline"]
